
export type IndexType = {
  showGrid: boolean,
  type: string,
  size: number,
  color: string,
  thickness: number,
  colorSecond: string,
  thicknessSecond: number,
  factor: number
  bgColor: string,
  showImage: boolean,
  repeat: string,
  angle: number,
  position: string,
  bgSize: string,
  opacity: number,

  strokeWidth: number,
  outStrokeWidth: number,
  stroke: string,
  outStroke: string,
  strokeDasharray: number,
  animation: number,
  connector: string,
  edgeRouter: string,
  edgeOffset: number,
  edgeDirection: string,
  label: string,

  nodeStroke: string,
  nodeStrokeWidth: number,
  nodeFill: string,
  // nodeImageWidth: number,
  // nodeImageHeight: number,
  portId: string,
  portX: number | string,
  portY: number | string,
  portColor: string,
  portFill: string,
  ZIndex: number,
  nodeFontSize: number,
  nodeColor: string,
  nodeStatus: string,
  nodePointCode: string,
  nodeFieldName: string,

  nodeType: string // 节点类型(text、image)
}